<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| **Term**   | **Brief description**                                                                                                                                     |
|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Subsetting | Selecting a part of a list/NumPy array                                                                                                                    |
| Indexing   | One type of subsetting which selects one element from a list/NumPy array                                                                                  |
| Slicing    | Another type of subsetting which selects a range of elements from a list/NumPy array                                                                      |
| Masking    | Another type of subsetting which selects a part of a list/NumPy array based on some criteria (including using bitwise operators such as AND, OR, or NOT)  |

# Exercise 2

In [18]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

# convert all the numbers into integers 
array_ele1 = np_array_2d[:,0].astype(int)
# check for the odd ones
array_ele1_odd = array_ele1 % 2
# masking for the odd ones
odd_mask = array_ele1_odd == 1
# applying the mask to the original array then printing it
odd_letters = np_array_2d[odd_mask][:,1]
print(odd_letters)

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [25]:
import numpy as np

np_2d_array = np.array(
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

# make masks
less_50_mask = np_2d_array < 50
more_50_mask = np_2d_array > 50
equal_50_mask = np_2d_array == 50

# change the values according to the masks
np_2d_array[less_50_mask] = -1
np_2d_array[more_50_mask] = 1
np_2d_array[equal_50_mask] = 0

print(np_2d_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
